Separate popup from calendar
bem/bem-calendar pull request #23
Opened 2017-02-28 20:45 UTC by VladimirMilenko

1. Calendar now can be used as a separate block, input has modifier _has-calendar, which controls popup itself.
2. Calendar now supports `selectedDayElement` property, which is used to indicate selected day when using calendar as a separate block.

2017-03-02 16:49 UTC, tadatuta requested changes

2017-03-02 16:49 UTC, tadatuta commented on common.blocks/calendar/calendar.bemhtml.js
> +block('calendar');
если шаблон не делает ничего полезного, то стоит его удалить целиком

2017-03-02 16:49 UTC, tadatuta commented on common.blocks/calendar/calendar.bh.js
> +module.exports = function() {
same shit

2017-03-02 16:49 UTC, tadatuta commented on package.json
> +    "fix":"elsint . --fix",
тут как минимум не хватает пробела после `:`, но я бы целиком выпилил, т.к. изменение не имеет отношения к тему PR

2017-03-02 16:49 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +        for(var i = 0; i < dayElems._entities.length;i++) {
dayElems._entities.length -> dayElems.size()

2017-03-02 16:49 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +            if(dayElems._entities[i].hasMod('state', 'current')) {
`dayElems.get(i)`

2017-03-02 16:49 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +    _findSelectedDay: function() {
дочитал код метода, понял, что он целиком сводится к
```js
return this.findChildElems({ elem: 'day', modName: 'state', modVal: 'current' });
```

2017-03-02 16:49 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +        if(this._selectedDayElem) {
не хочешь эту проверку внутрь метода `_selectDayElem` унести?

2017-03-02 16:49 UTC, tadatuta commented on common.blocks/input/_has-calendar/input_has-calendar.js
> +     * Is shown calendar?
Is shown calendar? -> Is calendar shown

2017-03-02 19:26 UTC, tadatuta requested changes

2017-03-02 19:26 UTC, tadatuta commented on common.blocks/calendar/calendar.deps.js
>              mods: { theme: 'islands' }
чтобы заработали поинтер-события, нужно в зависимости добавить
```js
{ block: 'jquery', elem: 'event', mods: { type: 'pointer' } }
```

2017-03-02 19:26 UTC, tadatuta commented on common.blocks/calendar/calendar.deps.js
>              mods: { theme: 'islands' }
а для того, чтобы шаблоны подтянулись на клиент, нужно что-то типа
```js
[
    {
        mustDeps: {
            block: 'i-bem-dom'
        },
        shouldDeps: [
            { block : 'jquery', elem : 'event', mods : { type : 'pointer' } },
            {
                elems: ['arrow', 'day', 'dayname']
            },
            {
                mods: { theme: 'islands' }
            }
        ]
    },
    {
        tech: 'js',
        shouldDeps: {
            tech: 'bemhtml'
        }
    }
];
```

но я пока не уверен, что это в принципе хорошо.
Как минимум нужен способ через API задать произвольную дату заранее, а еще лучше — мочь рендерить календарь заранее на сервере. Но может и не нужно пытаться сделать такое изменение за один раз. В общем, пока думаю.

2017-03-02 19:26 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +        this._selectedDayElem = this._findSelectedDay();
если метод используется только один раз и не причин хотеть его переопределять, может просто заинлайнить его прямо здесь?

2017-03-02 19:26 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +    _selectDayElem: function(element) {
есть стойкое ощущение, что эта логика должна быть в `setVal`, т.к. иначе при изменении даты через JS API текущий элемент не выбранный элемент не изменится

2017-03-02 19:26 UTC, tadatuta commented on common.blocks/calendar/calendar.js
>              '': function() {
в текущем виде эту секцию можно смело выпилить, i-bem сам позаботится обо всем

2017-03-02 21:26 UTC, tadatuta requested changes

2017-03-02 21:26 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +                    this.findChildElems('day')
лучше `this._elems('day')`

2017-03-02 21:26 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +            indexSet = false;
булевые переменные принято начинать на `is` или `has`

2017-03-02 21:26 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +        if(!date)            {return;}
странное форматирование

2017-03-06 14:48 UTC, tadatuta requested changes

2017-03-06 14:48 UTC, tadatuta commented on common.blocks/calendar/calendar.deps.js
> +            { block: 'i-bem-dom' },
мне предыдущий вариант форматирования нравится больше

2017-03-06 14:48 UTC, tadatuta commented on common.blocks/calendar/calendar.deps.js
> +
лишняя строка

2017-03-06 14:48 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +                if(this._isValidDate(this.params.val)) {
можно сократить до
```js
this.setVal(this._isValidDate(this.params.val) ? this.params.val : today);
```

2017-03-06 14:48 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +            isIndexSet = false;
не получится избавиться от флага, если не создавать `_firstDayIndex` в конструкторе?

2017-03-06 15:34 UTC, birhoff commented on common.blocks/calendar/calendar.deps.js
> +                mods: { theme: 'islands' }
А что делает этот модификатор для календаря?

2017-03-06 15:34 UTC, birhoff commented on common.blocks/calendar/calendar.js
> -        this.hide();
Кажется вот это нарушает обратную совместимость, так как я не нашел эту строку в календаре с попапом.

2017-05-07 04:04 UTC, closed without merging