North-American date and calendar format
bem/bem-calendar pull request #9
Opened 2017-02-18 14:24 UTC by VladimirMilenko

NA format now depends on `format` modifier.
Adds support for `mm/dd/yyyy' format and sets Sunday as a first day in a week.

2017-02-18 15:45 UTC, tadatuta requested changes

2017-02-18 15:45 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +            _this = this;
вместо сохранения `this`, лучше передать его в `forEach` последним аргументом

2017-02-18 15:45 UTC, tadatuta commented on common.blocks/input/_has-calendar/input_has-calendar.bh.js
> +                    format: ctx.node.mods ? ctx.node.mods['calendar-format'] : false
должно быть аналогично и для bemhtml-шаблонов?
кстати, там всегда доступно `this.mods`, так что проверять на его существование не нужно.

а здесь можно чуть сократить:
```js
format: ctx.node.mods && ctx.node.mods['calendar-format']
```

2017-02-18 15:45 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +    provide(bemDom.declMod({ modName: 'format', modVal: 'north-american' }, {
bemDom.declMod -> `Calendar.declMod`

2017-02-18 15:45 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +modules.define('calendar', ['i-bem-dom'], function(provide, Calendar, bemDom) {
сработало случайно, т.к. неправильный порядок аргументов.
работает так: первый всегда `provide` потом все зависимости и последним аргументом предыдущая реализация текущего модуля.

но судя по коду здесь `i-bem-dom` вообще не нужен.

2017-02-18 16:29 UTC, tadatuta requested changes

2017-02-18 16:29 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +                    this._formatDate = formatDate;
стоит переопределять прямо как в базовой реализации:

```js
{
    onSetMod: { /* ... */ },
    _formatDate: function() {}
}
```
и так далее

2017-02-18 16:29 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +    function parseDate(val) {
нужно положить `parseDateParts` как `_parseDateParts` в прототип в базовой декларации, а здесь его переопределить так, чтобы вообще не потребовалось переопределять `parseDate`. вроде должно получиться.

2017-02-18 16:29 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +    function calcWeeks(month) {
сильно не вчитывался, поэтому спрошу наугад: не получится в `calcWeeks()` сделать что-то в духе
```js
var weeks = this.__base.apply();
// тут проитерироваться по weeks и внести изменения
return weeks;
```
?

2017-02-18 16:29 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +    function parseDateParts(str) {
думаю, стоит попробовать в базовой реализации переписать так, чтобы возвращался не массив, а хеш, тогда здесь не придется переопределять

2017-02-18 17:04 UTC, skad0 commented on common.blocks/calendar/calendar.js
> +            _this = this;
У нас тут вообще node >= 4, можно и стрелочную функцию юзануть

2017-02-18 17:58 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +            _this = this;
воу, это клиентский js, никаких стрелочных функций

2017-02-18 18:03 UTC, skad0 commented on common.blocks/calendar/calendar.js
> +            _this = this;
Действительно, завтыкал

2017-02-18 19:44 UTC, tadatuta requested changes

2017-02-18 19:44 UTC, tadatuta commented on common.blocks/calendar/calendar.deps.js
> +            mods: { theme: 'islands', format: 'north-american' }
эта зависимость должна добавляться на уровне проекта, когда `north-american` действительно нужен, иначе лишний код приедет всем

2017-02-18 19:44 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +        onSetMod: {
если ничего не переопределяется, то всю секцию `onSetMod` можно не писать

2017-02-18 19:44 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +        _formatDate: function() {
похоже, что здесь вызов базового метода и своп не дают особой экономии по коду, предлагаю написать «с нуля» (могут быть опечатки):

```js
_formatDate: function(date) {
    var month = date.getMonth() + 1,
        day = date.getDate();

    return [month < 10 ? '0' + month, day < 10 ? '0' + day, date.getFullYear()].join('/');
}
```

2017-02-18 19:44 UTC, tadatuta commented on common.blocks/calendar/calendar.js
> +        match = /^\s*(\d{1,2})[./-](\d{1,2})(?:[./-](\d{4}|\d\d))?\s*$/.exec(str);
раз уж трогаем этот кусок, давай объединим объявление и присвоение в одну строку?

2017-02-18 19:44 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +            ) {
если я правильно смотрю, то `_calcWeeks` отличается только телом цикла. если так, то его можно вынести в отдельный метод и переопределять только его, чтобы не плодить копипаст.

2017-02-18 19:51 UTC, tadatuta commented on README.md
> +        format: 'north-american'
в коде поле называется `calendar-format`

2017-02-18 20:58 UTC, tadatuta commented
Я погорячился на счет зависимостей от `calendar_format_north-americal` на уровне проекта, на самом деле их логично добавить в `input_calendar-format_north-american.deps.js`

2017-02-18 21:01 UTC, tadatuta commented on common.blocks/calendar/_format/calendar_format_north-american.js
> +
вкусовщина: я бы эту строку прибил, а вот перед `return` добавил

2017-02-18 21:03 UTC, tadatuta commented
@birhoff взглянешь?

2017-02-19 00:55 UTC, tadatuta approved these changes

2017-02-20 15:13 UTC, birhoff approved these changes

2017-02-20 19:21 UTC, merged